# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CWPhotoBrowser' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kingfisher'
  pod 'SnapKit'

end

target 'CWPhotoBrowserDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kingfisher'
  pod 'SnapKit'

  # Pods for CWPhotoBrowserDemo
  target 'CWPhotoBrowserDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
